version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    env_file:
      - .env
    # Other configuration options for the backend service

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    # Other configuration options for the frontend service
