version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - 8080:8080
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
