version: '3'
services:
  backend:
    build:
      context: ./backend
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    ports:
      - 8080  # Backend service is not exposed to the outside world
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - 8081:3000  # Expose frontend service on port 8081 of the host machine
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
