version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    environment:
      - DB_HOST=<POSTGRES_HOST>
      - DB_USER=<POSTGRES_USER>
      - DB_PASSWORD=<POSTGRES_PASSWORD>
      - DB_NAME=<POSTGRES_DB_NAME>
      - DB_PORT=<POSTGRES_PORT>

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
